### ISSUE TITLE
"DOMException: The specified interface has not been claimed." when keyboard is used

### ISSUE THREAD

**Issue by DeqingSun** [webusb/arduino#23]
Hi,

I got Arduino working with examples. But when I put
# include "Keyboard.h"

in sketch, the interface can not be claimed. I tried to change interface number in serial.js with no luck.

Tested on Mac OS 10.10.5

**Comment by DeqingSun** [comment]
My bad, 
all endpoints in 
transferIn,claimInterface,controlTransferOut,transferOut
need to be increased by 1.

**Comment by reillyeon** [comment]
Good to know what works as I expected it would. I was about to pull out my Arduino to try to reproduce.
