### ISSUE TITLE
README should mention USB 2.1 requires BOS

### ISSUE THREAD

**Issue by mon** [webusb/arduino#25]
I'm working on WebUSB additions to the LUFA USB stack and am using this Arduino implementation as my working benchmark.

I'm affected by #4 so I was starting to poke things, and loaded a sketch which didn't #include WebUSB.h. Because I'm not providing a BOS, Windows fails to enumerate my device and I can no longer program it.

I'll dig up the ISP, but it might be worth mentioning to those who may try WebUSB then go back to an older sketch that doesn't use it. Could possibly also change the installation to use the new boards that have been defined?

**Comment by q2dg** [comment]
Maybe this is related: https://github.com/arduino/Arduino/pull/6147
