### ISSUE TITLE
How to upgrade to USB 2.1 from Arduino Web Editor?

### ISSUE THREAD

**Issue by varunkumar** [webusb/arduino#39]
> The WebUSB library provides all the extra low-level USB code necessary for WebUSB support except for one thing: Your device must be upgraded from USB 2.0 to USB 2.1. To do this go into the SDK installation directory and open hardware/arduino/avr/cores/arduino/USBCore.h. Then find the line #define USB_VERSION 0x200 and change 0x200 to 0x210. That's it!

Is it possible to do this from Arduino Web Editor?

**Comment by reillyeon** [comment]
While newer versions of the native Arduino SDK support modifying the board configuration to change USB_VERSION this does not appear to be possible with the web editor. I suggest reaching out through Arduino's support channels to request this feature.
