### ISSUE TITLE
Be consistent with #include <WebUSB.h> in demos

### ISSUE THREAD

**Issue by beaufortfrancois** [webusb/arduino#5]
https://github.com/webusb/arduino/blob/4777ab7badfd13be5b8efc7cedc190ca309e4719/demos/rgb/sketch/sketch.ino#L1 includes `WebUSB.h` while https://github.com/webusb/arduino/blob/4777ab7badfd13be5b8efc7cedc190ca309e4719/demos/console/sketch/sketch.ino doesn't.

It would be nice for consistency to either remove it or include it and update README instructions.

**Comment by reillyeon** [comment]
The console demo sketch was written to an older version of the WebUSB support library that didn't require the include. It should be updated.
