### ISSUE TITLE
Significant delay in WebUSB::operator bool()

### ISSUE THREAD

**Issue by DeqingSun** [webusb/arduino#50]
The delay in WebUSB::operator bool() will introduce a huge delay in the main loop if the user checks it every time.

What is the bug found by Federico? I can not find any info on Github, but there should be a better way to fix it.

**Comment by jpliew** [comment]
@DeqingSun it looks like the comment was before code was first committed to this repo.

If your sketch is not sending messages to the host, you can ignore it and not necessarily need to check the return status.

**Comment by reillyeon** [comment]
This file is a copy of [CDC.cpp](https://github.com/arduino/Arduino/blob/master/hardware/arduino/avr/cores/arduino/CDC.cpp) out of the Arduino SDK with modifications as described in README.md.
