### ISSUE TITLE
WebUSB.h:33:2: error: "WebUSB requires a board that supports USB client device mode."

### ISSUE THREAD

**Issue by ghost** [webusb/arduino#51]
in file included from /Users/t.shivam/Downloads/arduino-gh-pages/demos/console/sketch/sketch.ino:1:0:
/Users/t.shivam/Documents/Arduino/libraries/WebUSB/WebUSB.h:33:2: error: #error "WebUSB requires a board that supports USB client device mode."
 #error "WebUSB requires a board that supports USB client device mode."
  ^
exit status 1
Error compiling for board Arduino/Genuino Uno.

I am getting this error after loading and uploading th sketch to my arduino. I tried googling but no leads. Any idea why this is happening?

**Comment by tylercrumpton** [comment]
The Arduino/Genuino Uno does not support WebUSB. You'll want one of these boards instead:

* Arduino Leonardo
* Arduino/Genuino Micro
* Arduino/Genuino Zero
* Arduino MKR1000
* Arduino MKRZero
* Arduino MKRFox1200
* Adafruit Feather 32u4
