### ISSUE TITLE
no notification in windows or android

### ISSUE THREAD

**Issue by jimvdH** [webusb/arduino#59]
I uploaded the code to my leonardo and the web USB seems to work when I manually go to the website. But neither in Windows, Linux or in Android I get a website notification with where to go.  I know this notification isn't working windows, but android should give a pop-up I guess? 

like this example 
![image](https://user-images.githubusercontent.com/34292867/50241449-cdf0db00-03c7-11e9-977e-09ceddb09916.png)

**Comment by reillyeon** [comment]
I just pushed a change to README.md highlighting that the notification does not appear on Android because unfortunately the OS prevents the browser from connecting to the device until there is a user interaction.
