### ISSUE TITLE
Bricked MKRZero

### ISSUE THREAD

**Issue by lbrutti** [webusb/arduino#75]
Hello everyone,
I bricked my MKRZERO by setting 
`#define USB_VERSION 0x200`

to 0x20**1** instead of **0x210**

Anybody knows how to debrick it?

I have an Arduino Uno, MKR1400 and MKR1300: can I use one of them to reflash the bootloader?

thanks

**Comment by reillyeon** [comment]
What host OS are you running? For the most part macOS and Linux are much more flexible about ignoring weird USB versions.

**Comment by lbrutti** [comment]
Windows 10, but I also have a MacBook: do you think that loading a sketch
from osx will unbrick the board?

--
Sent from Android

Il gio 23 apr 2020, 01:25 Reilly Grant <notifications@github.com> ha
scritto:

**Comment by ubidefeo** [comment]
@lbrutti 
if the IDE sees your board (although the VID/PID) won't let it automatically recognise it, 
just manually select the MKRZERO as a target and the serial port and flash a blink sketch.
Every time you program one of the MKR boards, the VID/PID pair is reflashed

**Comment by ubidefeo** [comment]
@lbrutti I think I misunderstood the issue there

**Comment by lbrutti** [comment]
> What host OS are you running? For the most part macOS and Linux are much more flexible about ignoring weird USB versions.

@reillyeon : unfortunately neither OSx sees the board as attached to serial port.

Is there a procedure to burn the bootloader again as in https://www.instructables.com/id/How-to-fix-bad-Chinese-Arduino-clones/ ?

**Comment by ubidefeo** [comment]
@lbrutti 
you can burn the bootloader only if you use an openOCD compatible programmer.
Atmel ICE
BlackMagic Probe
J-Link

**Comment by lbrutti** [comment]
I managed to recover the board by pressing reset twice...I wasn't double pressing fast enough.

Thanks to all!
