### ISSUE TITLE
WebUSB on local webpage

### ISSUE THREAD

**Issue by grimedirective** [webusb/arduino#81]
Hi there,
I used the example Arduino sketches and I am able to access the device via the example web page. However when I launch the sample pages from the local GitHub download, I do not have the same ability to communicate with the Arduino.

Is it a requirement for the library to function through the internet?

**Comment by jpliew** [comment]
If you are opening the html file directly from a browser, it will not work.

If you would like to develop locally, please setup a local web server and host the file from localhost.

Open the URL from the browser pointing to for example, `http://localhost/arduino/demos/console/`

Hope this helps.
