### ISSUE TITLE
Is webUSB supported for Arduino Uno R3

### ISSUE THREAD

**Issue by Gaurav-Ramakrishna** [webusb/arduino#85]
Everytime I verify the skecth file I get the error,
`Error compiling for board Arduino Uno.
`

**Comment by reillyeon** [comment]
The error complete message should give you a hint here. This library requires a board which supports USB client mode, which the Arduino Uno series does not. For this and other similar boards I recommend the [Web Serial API](https://web.dev/serial).

**Comment by Gaurav-Ramakrishna** [comment]
ok thanks
